install:
- . ./profile.sh
- ./install-dependencies.sh

script:
- . ./profile.sh
- PATH=$PATH:$HOME/.local/bin make doc build
- adventure

env:
  matrix:
    - CWEB_VERSION=cweb-3.43
    - CWEB_VERSION=cweb-3.64c
  global:
    - Build_Deps_Default_Paths=1
